### ISSUE TITLE
problem executing example 10-stress.py

### ISSUE THREAD

**Issue by caperott** [fishjojo/pyscfad#34]
I am getting a persistent error message running the example https://github.com/fishjojo/pyscfad/blob/main/examples/pbc/scf/10-stress.py

jax.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on traced array with shape float64[3,3].

I am running an environment with
pyscfad in pyscfad_env/lib/python3.12/site-packages (0.1.5)
numpy>=1.17 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (1.26.4)
scipy<1.12 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (1.11.4)
h5py in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (3.11.0)
jax>=0.3.25 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (0.4.30)
jaxlib>=0.3.25 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (0.4.30)
pyscf>=2.3 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (2.6.2)
pyscfadlib>=0.1.4 in pyscfad_env/lib/python3.12/site-packages (from pyscfad) (0.1.5)
ml-dtypes>=0.2.0 in pyscfad_env/lib/python3.12/site-packages (from jax>=0.3.25->pyscfad) (0.4.0)
opt-einsum in pyscfad_env/lib/python3.12/site-packages (from jax>=0.3.25->pyscfad) (3.3.0)
setuptools in pyscfad_env/lib/python3.12/site-packages (from pyscf>=2.3->pyscfad) (70.0.0)

Any help is very welcome!

**Comment by fishjojo** [comment]
Thanks for raising this. The issue should be fixed in [1921947](https://github.com/fishjojo/pyscfad/commit/19219479a3b6b661a1e69698c83933b76e1a28da).
Please note that the current implementation is for illustration only, which is very slow and requires a lot of memory since the response of the uniform grid is needed. I don't have plan to improve it unless there is any related interesting research problem.

**Comment by caperott** [comment]
Thank you very much for getting this fixed!!
